version: "3"
services:
        webserver:
                image: nginx:latest
                restart: always
                ports:
                        - 8080:80
                volumes:
                        - /home/meghana/dockerfile/websites:/usr/share/nginx/html




